# Generated by Django 5.2.8 on 2025-12-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mission_name", models.CharField(max_length=255)),
                (
                    "era",
                    models.CharField(
                        choices=[
                            ("Ancient", "Ancient Era"),
                            ("Medieval", "Medieval Era"),
                            ("Colonial", "Colonial Era"),
                            ("Modern", "Modern Era"),
                            ("Independence", "Independence Era"),
                        ],
                        max_length=32,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("visited_at", models.DateTimeField()),
                ("progress", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-visited_at"],
                "indexes": [
                    models.Index(
                        fields=["-visited_at"], name="missions_mi_visited_f5a8f4_idx"
                    )
                ],
            },
        ),
    ]
